[package]
name = "qpy_feeder"
version = "0.1.0"
authors = ["LuisAyuso <luis.f.ayuso@gmail.com>"]
edition = "2018"

[dependencies]
qpy_core = { path = "../qpy_core"}
rss = "1.6.1"
atom_syndication = "0.6.0"
reqwest = "0.9.5"
stringreader = "0.1.1"
ammonia = "1.2.0"
scraper = "0.8.1"