[package]
name = "elm_generator"
version = "0.1.0"
authors = ["LuisAyuso <luis.f.ayuso@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true


[dependencies]
quote = "0.6"
itertools = "0.7.11"


[dependencies.syn]
version = "0.15"
features = ["visit", "extra-traits"]
